[directory]
disabled = false
home_symbol = "ðŸ "
style = "#66b2b2" # teal from tmux status bar

[character]
error_symbol = "[>](red)"
success_symbol = "[>](purple)"
vicmd_symbol = "[<](green)"

[cmd_duration]
format = " [$duration]($style) "
style = "#fcff54"                # yellow

[battery]
charging_symbol = 'ðŸª«'
full_symbol = 'ðŸ”‹'

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
conflicted = "âš¡"
deleted = "ï‘˜ "
format = "[[( $conflicted$untracked$modified$staged$renamed$deleted)]($style) ($ahead_behind)]($style)"
modified = "âœ—"
renamed = "âžœ"
staged = "âœ“"
style = "bold red"
untracked = "âœ·"

[python]
# does '(venv_name)' when in virtual env
format = ' [(\($virtualenv\))]($style) '
style = "bold red"
symbol = ''
version_format = ''

[package]
disabled = true

[hostname]
disabled = true

[username]
disabled = true

[docker_context]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[lua]
disabled = true

[terraform]
disabled = true
