[directory]
disabled = false
style = "#66b2b2" # teal from tmux status bar
home_symbol = "ðŸ "

[character]
success_symbol = "[>](purple)"
error_symbol = "[>](red)"
vicmd_symbol = "[<](green)"

[cmd_duration]
format = " [$duration]($style) "
style = "#fcff54"                # yellow

[battery]
charging_symbol = 'ðŸª«'
full_symbol = 'ðŸ”‹'

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[( $conflicted$untracked$modified$staged$renamed$deleted)]($style) ($ahead_behind)]($style)"
style = "bold red"
conflicted = "âš¡"
untracked = "âœ·"
modified = "âœ±"
staged = "âœ“"
renamed = "âž¤"
deleted = "âœ—"

[package]
disabled = true

[hostname]
disabled = true

[username]
disabled = true

[python]
# does '(venv_name)' when in virtual env
format = ' [(\($virtualenv\))]($style) '
symbol = ''
version_format = ''
style = "bold red"

[docker_context]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[lua]
disabled = true

[terraform]
disabled = true
