[directory]
disabled = false
#truncation_length = 1
style = "blue"
home_symbol = "ðŸ "

[character]
success_symbol = "[>](purple)"
error_symbol = "[>](red)"
vicmd_symbol = "[<](green)"

[cmd_duration]
format = " [$duration]($style) "
style = "#fcff54" # yellow

[battery]
charging_symbol='ðŸª«'
full_symbol='ðŸ”‹'

[package]
disabled = true

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
disabled = false
format = "[[( $conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "âš¡"
untracked = "âœ·"
modified = "âœ±"
staged = "âœ“"
renamed = "âž¤"
deleted = "âœ—"
stashed = "â‰¡"

[hostname]
disabled = true

[username]
disabled = true

[python]
# does '(venv_name)' when in virtual env
format = ' [(\($virtualenv\))](bold red) '
symbol = ''
version_format = ''

[docker_context]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[lua]
disabled = true
