# https://alacritty.org/config-alacritty.html
# may need to run `sudo ln -s /Applications/Alacritty.app/Contents/MacOS/Alacritty /usr/local/bin/alacritty`


[env]
# for true color support
# https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
TERM = "xterm-256color"

# DOWNLOAD HERE: https://www.nerdfonts.com/font-downloads
# must be a "Nerd Font" for icons to work on nvim-tree
# OLD FONTS:
# - Hack Nerd Font
# - JetBrainsMono Nerd Font

# NOTE: @joeyagreco - can use an alacritty.local.sh file to overwrite these fonts locally (JetBrainsMono / JetBrainsMonoNL)
# NOTE: @joeyagreco - would look something like this:

###############################################################
# FONT="JetBrainsMonoNL Nerd Font"
#
# # only send alacritty messages if we're running inside alacritty
# if [[ "$TERM_PROGRAM" == "Alacritty" ]] && [[ -n "$ALACRITTY_SOCKET" ]]; then
# 	alacritty msg config "font.normal.family='${FONT}'" 2>/dev/null &
# 	alacritty msg config "font.bold.family='${FONT}'" 2>/dev/null &
# 	alacritty msg config "font.italic.family='${FONT}'" 2>/dev/null &
# 	alacritty msg config "font.bold_italic.family='${FONT}'" 2>/dev/null &
# 	wait
# fi
###############################################################

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
# how many lines of scrollback to keep,
# '0' will disable scrolling.
history = 10000

[selection]
save_to_clipboard = true

[terminal.shell]
args = [ "-l" ]
program = "/bin/zsh"

[window]
decorations = "none"       # no top bar when not in macos fullscreen
startup_mode = "Maximized"

[terminal]

# NOTE: - this is so i can do SHIFT+RETURN while in claude code for a new line lol
[[keyboard.bindings]]
chars = "\n"
key = "Return"
mods = "Shift"
