# https://mise.jdx.dev/configuration.html#global-config-config-mise-config-toml
# https://mise.jdx.dev/configuration.html#configuration
[tools]
go = "1.23.2"
neovim = "0.11.6"
node = "latest"
python = [ "3.13" ]

[settings]
disable_hints = [ "*" ]
idiomatic_version_file_enable_tools = [ "python" ]
quiet = false
